### ISSUE TITLE
`on_module': wrong number of arguments (3 for 1..2)

### ISSUE THREAD

**Issue by mperham** [tmm1/ripper-tags#25]
Ruby 2.0.0-p353

```
/Users/mikep/.gem/ruby/2.0.0/gems/ripper-tags-0.1.3/lib/ripper-tags/parser.rb:287:in `on_module': wrong number of arguments (3 for 1..2) (ArgumentError)
	from /Users/mikep/.gem/ruby/2.0.0/gems/ripper-tags-0.1.3/lib/ripper-tags/parser.rb:252:in `process'
	from /Users/mikep/.gem/ruby/2.0.0/gems/ripper-tags-0.1.3/lib/ripper-tags/parser.rb:248:in `block in process'
	from /Users/mikep/.gem/ruby/2.0.0/gems/ripper-tags-0.1.3/lib/ripper-tags/parser.rb:248:in `each'
	from /Users/mikep/.gem/ruby/2.0.0/gems/ripper-tags-0.1.3/lib/ripper-tags/parser.rb:248:in `process'
	from /Users/mikep/.gem/ruby/2.0.0/gems/ripper-tags-0.1.3/lib/ripper-tags/parser.rb:281:in `on_module_or_class'
	from /Users/mikep/.gem/ruby/2.0.0/gems/ripper-tags-0.1.3/lib/ripper-tags/parser.rb:288:in `on_module'
	from /Users/mikep/.gem/ruby/2.0.0/gems/ripper-tags-0.1.3/lib/ripper-tags/parser.rb:252:in `process'
	from /Users/mikep/.gem/ruby/2.0.0/gems/ripper-tags-0.1.3/lib/ripper-tags/parser.rb:248:in `block in process'
	from /Users/mikep/.gem/ruby/2.0.0/gems/ripper-tags-0.1.3/lib/ripper-tags/parser.rb:248:in `each'
	from /Users/mikep/.gem/ruby/2.0.0/gems/ripper-tags-0.1.3/lib/ripper-tags/parser.rb:248:in `process'
	from /Users/mikep/.gem/ruby/2.0.0/gems/ripper-tags-0.1.3/lib/ripper-tags/parser.rb:228:in `initialize'
	from /Users/mikep/.gem/ruby/2.0.0/gems/ripper-tags-0.1.3/lib/ripper-tags/data_reader.rb:122:in `new'
	from /Users/mikep/.gem/ruby/2.0.0/gems/ripper-tags-0.1.3/lib/ripper-tags/data_reader.rb:122:in `tag_extractor'
```

**Comment by mislav** [comment]
This was fixed in #23; thanks for reporting
