### ISSUE TITLE
Can't make it work recursively

### ISSUE THREAD

**Issue by mlhamel** [tmm1/ripper-tags#47]
When running ripper-tags with `-R` it should failed and crash:

```
$ ripper-tags -r
/Users/mlhamel/.gem/ruby/2.0.0/gems/ripper-tags-0.2.0/lib/ripper-tags/parser.rb:303:in `on_assign': wrong number of arguments (6 for 3) (ArgumentError)
	from /Users/mlhamel/.gem/ruby/2.0.0/gems/ripper-tags-0.2.0/lib/ripper-tags/parser.rb:256:in `process'
	from /Users/mlhamel/.gem/ruby/2.0.0/gems/ripper-tags-0.2.0/lib/ripper-tags/parser.rb:233:in `initialize'
	from /Users/mlhamel/.gem/ruby/2.0.0/gems/ripper-tags-0.2.0/lib/ripper-tags/data_reader.rb:124:in `new'
	from /Users/mlhamel/.gem/ruby/2.0.0/gems/ripper-tags-0.2.0/lib/ripper-tags/data_reader.rb:124:in `tag_extractor'
	from /Users/mlhamel/.gem/ruby/2.0.0/gems/ripper-tags-0.2.0/lib/ripper-tags/data_reader.rb:95:in `block in each_tag'
	from /Users/mlhamel/.gem/ruby/2.0.0/gems/ripper-tags-0.2.0/lib/ripper-tags/data_reader.rb:58:in `block in each_file'
	from /Users/mlhamel/.gem/ruby/2.0.0/gems/ripper-tags-0.2.0/lib/ripper-tags/data_reader.rb:48:in `block (2 levels) in find_files'
	from /Users/mlhamel/.gem/ruby/2.0.0/gems/ripper-tags-0.2.0/lib/ripper-tags/data_reader.rb:48:in `block (2 levels) in find_files'
	from /Users/mlhamel/.gem/ruby/2.0.0/gems/ripper-tags-0.2.0/lib/ripper-tags/data_reader.rb:51:in `block in find_files'
	from /Users/mlhamel/.gem/ruby/2.0.0/gems/ripper-tags-0.2.0/lib/ripper-tags/data_reader.rb:42:in `each'
	from /Users/mlhamel/.gem/ruby/2.0.0/gems/ripper-tags-0.2.0/lib/ripper-tags/data_reader.rb:42:in `find_files'
	from /Users/mlhamel/.gem/ruby/2.0.0/gems/ripper-tags-0.2.0/lib/ripper-tags/data_reader.rb:48:in `block in find_files'
	from /Users/mlhamel/.gem/ruby/2.0.0/gems/ripper-tags-0.2.0/lib/ripper-tags/data_reader.rb:42:in `each'
	from /Users/mlhamel/.gem/ruby/2.0.0/gems/ripper-tags-0.2.0/lib/ripper-tags/data_reader.rb:42:in `find_files'
	from /Users/mlhamel/.gem/ruby/2.0.0/gems/ripper-tags-0.2.0/lib/ripper-tags/data_reader.rb:48:in `block in find_files'
	from /Users/mlhamel/.gem/ruby/2.0.0/gems/ripper-tags-0.2.0/lib/ripper-tags/data_reader.rb:42:in `each'
	from /Users/mlhamel/.gem/ruby/2.0.0/gems/ripper-tags-0.2.0/lib/ripper-tags/data_reader.rb:42:in `find_files'
	from /Users/mlhamel/.gem/ruby/2.0.0/gems/ripper-tags-0.2.0/lib/ripper-tags/data_reader.rb:58:in `each_file'
	from /Users/mlhamel/.gem/ruby/2.0.0/gems/ripper-tags-0.2.0/lib/ripper-tags/data_reader.rb:92:in `each_tag'
	from /Users/mlhamel/.gem/ruby/2.0.0/gems/ripper-tags-0.2.0/lib/ripper-tags.rb:145:in `block in run'
	from /Users/mlhamel/.gem/ruby/2.0.0/gems/ripper-tags-0.2.0/lib/ripper-tags/vim_formatter.rb:24:in `block in with_output'
	from /Users/mlhamel/.gem/ruby/2.0.0/gems/ripper-tags-0.2.0/lib/ripper-tags/default_formatter.rb:37:in `block in with_output'
	from /Users/mlhamel/.gem/ruby/2.0.0/gems/ripper-tags-0.2.0/lib/ripper-tags/default_formatter.rb:36:in `open'
	from /Users/mlhamel/.gem/ruby/2.0.0/gems/ripper-tags-0.2.0/lib/ripper-tags/default_formatter.rb:36:in `with_output'
	from /Users/mlhamel/.gem/ruby/2.0.0/gems/ripper-tags-0.2.0/lib/ripper-tags/vim_formatter.rb:21:in `with_output'
	from /Users/mlhamel/.gem/ruby/2.0.0/gems/ripper-tags-0.2.0/lib/ripper-tags.rb:144:in `run'
	from /Users/mlhamel/.gem/ruby/2.0.0/gems/ripper-tags-0.2.0/lib/ripper-tags.rb:126:in `call'
	from /Users/mlhamel/.gem/ruby/2.0.0/gems/ripper-tags-0.2.0/lib/ripper-tags.rb:126:in `block in process_args'
	from /Users/mlhamel/.gem/ruby/2.0.0/gems/ripper-tags-0.2.0/lib/ripper-tags.rb:114:in `block in option_parser'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/optparse.rb:885:in `initialize'
	from /Users/mlhamel/.gem/ruby/2.0.0/gems/ripper-tags-0.2.0/lib/ripper-tags.rb:33:in `new'
	from /Users/mlhamel/.gem/ruby/2.0.0/gems/ripper-tags-0.2.0/lib/ripper-tags.rb:33:in `option_parser'
	from /Users/mlhamel/.gem/ruby/2.0.0/gems/ripper-tags-0.2.0/lib/ripper-tags.rb:119:in `process_args'
	from /Users/mlhamel/.gem/ruby/2.0.0/gems/ripper-tags-0.2.0/bin/ripper-tags:10:in `<top (required)>'
	from /Users/mlhamel/.gem/ruby/2.0.0/bin/ripper-tags:23:in `load'
	from /Users/mlhamel/.gem/ruby/2.0.0/bin/ripper-tags:23:in `<main>'
```

**Comment by mislav** [comment]
Thanks for reporting. Running this command will generate ctags for each Ruby file individually:

```sh
find . -name '*.rb' -print -exec bundle exec ripper-tags -f /dev/null {} \;
```

Can you please run it to detect which file causes this error? Then, either send us the whole file, or if it's private, try to edit it down to a bare minimum that still reproduces your problem. The offending line seems to be an assignment of some sort.

**Comment by rahulkmr** [comment]
I am facing the same issue. I am running it as:

```
% ▶ ripper-tags  --exclude=.git --exclude=log -R . `rvm gemdir`/gems/* `rvm gemdir`/bundler/gems/*           
```

The offending file is `ruby-1.9.3-p448/lib/ruby/1.9.1/optparse.rb:882`. The offending file in the opening description is `ruby/2.0.0/optparse.rb:885`

The code in my version is:

```
  def initialize(banner = nil, width = 32, indent = ' ' * 4)
    @stack = [DefaultList, List.new, List.new]
    @program_name = nil
    @banner = banner
    @summary_width = width
    @summary_indent = indent
    @default_argv = ARGV
    add_officious
    yield self if block_given?
  end
```

882 is `yield self if block_given?`

**Comment by mislav** [comment]
I can't reproduce, unfortunately. Running ripper-tags on Ruby 2.0.0 for Ruby 1.9.3 source succeeds without errors. I can't see anything wrong with the `optparse.rb` source file.

Is there some other file that fails parsing? Try my `find` command above, but replace `.` with the list of files/directories you want searched.

**Comment by mislav** [comment]
Do you have extra information for me using my steps above to help me track this bug down? Otherwise I'm not able to reproduce.
