### ISSUE TITLE
Parsing error on the hanami-cli 0.1.0 gem

### ISSUE THREAD

**Issue by malin-as** [tmm1/ripper-tags#70]
This is the MWE that I extracted from the gem:
```ruby
class Mwe
  delegate %i[
    text
  ] => :symbol
end
```
When running `ripper-tags` on it, I get the following exception:
```
/home/malina/.rvm/gems/ruby-2.4.2/gems/ripper-tags-0.4.0/lib/ripper-tags/parser.rb:277:in `block in on_delegate': undefined method `first' for nil:NilClass (NoMethodError)
	from /home/malina/.rvm/gems/ruby-2.4.2/gems/ripper-tags-0.4.0/lib/ripper-tags/parser.rb:277:in `map'
	from /home/malina/.rvm/gems/ruby-2.4.2/gems/ripper-tags-0.4.0/lib/ripper-tags/parser.rb:277:in `on_delegate'
	from /home/malina/.rvm/gems/ruby-2.4.2/gems/ripper-tags-0.4.0/lib/ripper-tags/parser.rb:79:in `on_command'
	from /home/malina/.rvm/gems/ruby-2.4.2/gems/ripper-tags-0.4.0/lib/ripper-tags/data_reader.rb:156:in `parse'
	from /home/malina/.rvm/gems/ruby-2.4.2/gems/ripper-tags-0.4.0/lib/ripper-tags/data_reader.rb:156:in `parse_file'
	from /home/malina/.rvm/gems/ruby-2.4.2/gems/ripper-tags-0.4.0/lib/ripper-tags/data_reader.rb:164:in `tag_extractor'
	from /home/malina/.rvm/gems/ruby-2.4.2/gems/ripper-tags-0.4.0/lib/ripper-tags/data_reader.rb:136:in `block in each_tag'
	from /home/malina/.rvm/gems/ruby-2.4.2/gems/ripper-tags-0.4.0/lib/ripper-tags/data_reader.rb:69:in `resolve_file'
	from /home/malina/.rvm/gems/ruby-2.4.2/gems/ripper-tags-0.4.0/lib/ripper-tags/data_reader.rb:85:in `block in each_file'
	from /home/malina/.rvm/gems/ruby-2.4.2/gems/ripper-tags-0.4.0/lib/ripper-tags/data_reader.rb:98:in `each'
	from /home/malina/.rvm/gems/ruby-2.4.2/gems/ripper-tags-0.4.0/lib/ripper-tags/data_reader.rb:98:in `each_input_file'
	from /home/malina/.rvm/gems/ruby-2.4.2/gems/ripper-tags-0.4.0/lib/ripper-tags/data_reader.rb:84:in `each_file'
	from /home/malina/.rvm/gems/ruby-2.4.2/gems/ripper-tags-0.4.0/lib/ripper-tags/data_reader.rb:133:in `each_tag'
	from /home/malina/.rvm/gems/ruby-2.4.2/gems/ripper-tags-0.4.0/lib/ripper-tags.rb:199:in `block in run'
	from /home/malina/.rvm/gems/ruby-2.4.2/gems/ripper-tags-0.4.0/lib/ripper-tags/vim_formatter.rb:25:in `block in with_output'
	from /home/malina/.rvm/gems/ruby-2.4.2/gems/ripper-tags-0.4.0/lib/ripper-tags/default_formatter.rb:53:in `block in with_output'
	from /home/malina/.rvm/gems/ruby-2.4.2/gems/ripper-tags-0.4.0/lib/ripper-tags/default_formatter.rb:52:in `open'
	from /home/malina/.rvm/gems/ruby-2.4.2/gems/ripper-tags-0.4.0/lib/ripper-tags/default_formatter.rb:52:in `with_output'
	from /home/malina/.rvm/gems/ruby-2.4.2/gems/ripper-tags-0.4.0/lib/ripper-tags/vim_formatter.rb:22:in `with_output'
	from /home/malina/.rvm/gems/ruby-2.4.2/gems/ripper-tags-0.4.0/lib/ripper-tags.rb:198:in `run'
	from /home/malina/.rvm/gems/ruby-2.4.2/gems/ripper-tags-0.4.0/lib/ripper-tags.rb:180:in `call'
	from /home/malina/.rvm/gems/ruby-2.4.2/gems/ripper-tags-0.4.0/lib/ripper-tags.rb:180:in `block in process_args'
	from /home/malina/.rvm/gems/ruby-2.4.2/gems/ripper-tags-0.4.0/lib/ripper-tags.rb:162:in `block in option_parser'
	from /home/malina/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/optparse.rb:1062:in `initialize'
	from /home/malina/.rvm/gems/ruby-2.4.2/gems/ripper-tags-0.4.0/lib/ripper-tags.rb:73:in `new'
	from /home/malina/.rvm/gems/ruby-2.4.2/gems/ripper-tags-0.4.0/lib/ripper-tags.rb:73:in `option_parser'
	from /home/malina/.rvm/gems/ruby-2.4.2/gems/ripper-tags-0.4.0/lib/ripper-tags.rb:167:in `process_args'
	from /home/malina/.rvm/gems/ruby-2.4.2/gems/ripper-tags-0.4.0/bin/ripper-tags:15:in `<top (required)>'
	from /home/malina/.rvm/gems/ruby-2.4.2/bin/ripper-tags:23:in `load'
	from /home/malina/.rvm/gems/ruby-2.4.2/bin/ripper-tags:23:in `<main>'
	from /home/malina/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `eval'
	from /home/malina/.rvm/gems/ruby-2.4.2/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by mislav** [comment]
Thank you!
