### ISSUE TITLE
KeyError ("key not found: :name") in vim formatter

### ISSUE THREAD

**Issue by Mange** [tmm1/ripper-tags#87]
When encountering a `scope` with an empty name, `ripper-tags` crashes.

## Test case

**Example file**

```ruby
# foo.rb
scope '' do
  get :foo
end
```

**Command**

```bash
ripper-tags --version
ripper-tags foo.rb -f -
```

<details>
<summary><strong>Output</strong></summary>

```
ripper-tags 0.6.1
!_TAG_FILE_FORMAT       2       /extended format; --format=1 will not append ;" to lines/
!_TAG_FILE_SORTED       1       /0=unsorted, 1=sorted, 2=foldcase//home/mange/.rvm/gems/ruby-2.4.1/gems/ripper-tags-0.6.1/lib/ripper-tags/vim_formatter.rb:92:in `fetch': key not found: :name (KeyError)        from /home/mange/.rvm/gems/ruby-2.4.1/gems/ripper-tags-0.6.1/lib/ripper-tags/vim_formatter.rb:92:in `format'        from /home/mange/.rvm/gems/ruby-2.4.1/gems/ripper-tags-0.6.1/lib/ripper-tags/vim_formatter.rb:33:in `write'        from /home/mange/.rvm/gems/ruby-2.4.1/gems/ripper-tags-0.6.1/lib/ripper-tags.rb:210:in `block (2 levels) in run'        from /home/mange/.rvm/gems/ruby-2.4.1/gems/ripper-tags-0.6.1/lib/ripper-tags/data_reader.rb:160:in `block (2 levels) in each_tag'        from /home/mange/.rvm/gems/ruby-2.4.1/gems/ripper-tags-0.6.1/lib/ripper-tags/data_reader.rb:159:in `each'        from /home/mange/.rvm/gems/ruby-2.4.1/gems/ripper-tags-0.6.1/lib/ripper-tags/data_reader.rb:159:in `block in each_tag'        from /home/mange/.rvm/gems/ruby-2.4.1/gems/ripper-tags-0.6.1/lib/ripper-tags/data_reader.rb:66:in `resolve_file'        from /home/mange/.rvm/gems/ruby-2.4.1/gems/ripper-tags-0.6.1/lib/ripper-tags/data_reader.rb:99:in `block in each_file'        from /home/mange/.rvm/gems/ruby-2.4.1/gems/ripper-tags-0.6.1/lib/ripper-tags/data_reader.rb:112:in `each'        from /home/mange/.rvm/gems/ruby-2.4.1/gems/ripper-tags-0.6.1/lib/ripper-tags/data_reader.rb:112:in `each_input_file'        from /home/mange/.rvm/gems/ruby-2.4.1/gems/ripper-tags-0.6.1/lib/ripper-tags/data_reader.rb:98:in `each_file'        from /home/mange/.rvm/gems/ruby-2.4.1/gems/ripper-tags-0.6.1/lib/ripper-tags/data_reader.rb:150:in `each_tag'        from /home/mange/.rvm/gems/ruby-2.4.1/gems/ripper-tags-0.6.1/lib/ripper-tags.rb:209:in `block in run'        from /home/mange/.rvm/gems/ruby-2.4.1/gems/ripper-tags-0.6.1/lib/ripper-tags/vim_formatter.rb:25:in `block in with_output'        from /home/mange/.rvm/gems/ruby-2.4.1/gems/ripper-tags-0.6.1/lib/ripper-tags/default_formatter.rb:47:in `with_output'        from /home/mange/.rvm/gems/ruby-2.4.1/gems/ripper-tags-0.6.1/lib/ripper-tags/vim_formatter.rb:22:in `with_output'
        from /home/mange/.rvm/gems/ruby-2.4.1/gems/ripper-tags-0.6.1/lib/ripper-tags.rb:208:in `run'
        from /home/mange/.rvm/gems/ruby-2.4.1/gems/ripper-tags-0.6.1/lib/ripper-tags.rb:190:in `call'
        from /home/mange/.rvm/gems/ruby-2.4.1/gems/ripper-tags-0.6.1/lib/ripper-tags.rb:190:in `block in process_args'
        from /home/mange/.rvm/gems/ruby-2.4.1/gems/ripper-tags-0.6.1/lib/ripper-tags.rb:172:in `block in option_parser'
        from /home/mange/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/optparse.rb:1062:in `initialize'
        from /home/mange/.rvm/gems/ruby-2.4.1/gems/ripper-tags-0.6.1/lib/ripper-tags.rb:80:in `new'
        from /home/mange/.rvm/gems/ruby-2.4.1/gems/ripper-tags-0.6.1/lib/ripper-tags.rb:80:in `option_parser'
        from /home/mange/.rvm/gems/ruby-2.4.1/gems/ripper-tags-0.6.1/lib/ripper-tags.rb:177:in `process_args'
        from /home/mange/.rvm/gems/ruby-2.4.1/gems/ripper-tags-0.6.1/bin/ripper-tags:15:in `<top (required)>'
        from /home/mange/.rvm/gems/ruby-2.4.1/bin/ripper-tags:23:in `load'
        from /home/mange/.rvm/gems/ruby-2.4.1/bin/ripper-tags:23:in `<main>'
        from /home/mange/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
        from /home/mange/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
```

</details>

<details open>
<summary><strong>Cleaned up stack trace</strong></summary>

```
lib/ripper-tags/vim_formatter.rb:92:in `fetch': key not found: :name (KeyError)
lib/ripper-tags/vim_formatter.rb:92:in `format'
lib/ripper-tags/vim_formatter.rb:33:in `write'
lib/ripper-tags.rb:210:in `block (2 levels) in run'
lib/ripper-tags/data_reader.rb:160:in `block (2 levels) in each_tag'
lib/ripper-tags/data_reader.rb:159:in `each'
lib/ripper-tags/data_reader.rb:159:in `block in each_tag'
lib/ripper-tags/data_reader.rb:66:in `resolve_file'
lib/ripper-tags/data_reader.rb:99:in `block in each_file'
lib/ripper-tags/data_reader.rb:112:in `each'
lib/ripper-tags/data_reader.rb:112:in `each_input_file'
lib/ripper-tags/data_reader.rb:98:in `each_file'
lib/ripper-tags/data_reader.rb:150:in `each_tag'
lib/ripper-tags.rb:209:in `block in run'
lib/ripper-tags/vim_formatter.rb:25:in `block in with_output'
lib/ripper-tags/default_formatter.rb:47:in `with_output'
lib/ripper-tags/vim_formatter.rb:22:in `with_output'
lib/ripper-tags.rb:208:in `run'
lib/ripper-tags.rb:190:in `call'
lib/ripper-tags.rb:190:in `block in process_args'
lib/ripper-tags.rb:172:in `block in option_parser'
ruby-2.4.1/lib/ruby/2.4.0/optparse.rb:1062:in `initialize'
lib/ripper-tags.rb:80:in `new'
lib/ripper-tags.rb:80:in `option_parser'
lib/ripper-tags.rb:177:in `process_args'
bin/ripper-tags:15:in `<top (required)>'
```

</details>

**Comment by mislav** [comment]
Thank you for reporting!

**Comment by Mange** [comment]
Thank you!
